---
author: |
  | CPESR
  | [www.cpesr.fr](https://cpesr.fr)
  | contact@cpesr.fr
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output:
  beamer_presentation:
    # toc: true
    # toc_depth: 3
    number_sections: true
    slide_level: 2
    theme: "Madrid"
    includes:
      in_header: files/header.tex
      #before_body: before_body.tex
    keep_tex:  true
classoption: "aspectratio=169"
urlcolor: blue
linkcolor: white
fontsize: 8pt
lang: "fr-FR"
#geometry: margin=1.5cm
#documentclass: book
---

```{r config, include=FALSE}

rentrée.ref <- 2012
rentrée.last <- 2019

type <- "Universités et assimilés"
libellé <- "Université de Lorraine"
```

```{r child = '../fbpESR-main.Rmd', echo = FALSE, warning = FALSE}
```

<!-- ```{r child = '../fbpESR-extra-heures.Rmd', echo = FALSE, warning = FALSE} -->
<!-- ``` -->

<!-- ```{r child = '../fbpESR-extra-dotations.Rmd', echo = FALSE, warning = FALSE} -->
<!-- ``` -->

<!-- ```{r child = '../fbpESR-extra-liens.Rmd', echo = FALSE, warning = FALSE} -->
<!-- ``` -->

  
  