
```{r heures.setup, include=FALSE}
  knitr::opts_chunk$set(fig.width = 8, fig.height = 3, out.width = NULL, out.height = "40%", fig.align="center")
```


# Les heures d'enseignement

```{r plot_heePetu, results='asis', echo = FALSE, warning = FALSE, error=FALSE}
invisible(make_slide(plot_evolution, "kpi.H.heePetu", "Le nombre d'heures d'enseignement moyen par étudiant", 
"Le nombre d'heures d'enseignement moyen par étudiant est une mesure de la politique d'enseignement de l'établissement. Il reflète à la fois le volume d'heures délivré et la taille des groupes : il augmente avec la diversité de l'offre de formation et le nombre d'heures par formation, et il baisse avec le nombre d'étudiants par groupe. Il ne capture par l'hétérogénité des formations de l'établissement.",
"- L'évolution passée est-elle souhaitable, regrettable ou inévitable ?
- Quelle devra être l'évolution future et comment y arriver ? Avec quelle priorité ? ",
observation = TRUE))
```


```{r plot_hcvPhee, results='asis', echo = FALSE, warning = FALSE}
make_slide(plot_evolution, "kpi.H.hcvPhee", "Le taux d'heures d'enseignement complémentaires effectuées par des personnels non-titulaires", 
"Le taux d'heures d'enseignement complémentaires effectuées par des personnels non-titulaires est une mesure de la politique RH de l'établissement. Il indique la proportion des enseignements qui sont assurées par des vacataires.",
"- L'évolution passée est-elle souhaitable, regrettable ou inévitable ?
- Quelle devra être l'évolution future et comment y arriver ? Avec quelle priorité ? ",
observation = TRUE)
```


```{r plot_hctPtit, results='asis', echo = FALSE, warning = FALSE}
make_slide(plot_evolution, "kpi.H.hctPtit", "Les heures complémentaires moyennes par enseignant titulaire", 
"Les heures complémentaires moyennes par enseignant titulaire est une mesure des politiques RH et d'enseignement de l'établissement. Il indique, en moyenne, combien d'heures doivent effectuer les enseignants et enseignants-chercheurs au delà de leur service statutaire. Il ne permet pas de capturer l'hétérogénité de cette charge entre les personnels.",
"- L'évolution passée est-elle souhaitable, regrettable ou inévitable ?
- Quelle devra être l'évolution future et comment y arriver ? Avec quelle priorité ? ",
observation = TRUE)
```


