---
title: "versus"
author: "Julien Gossa"
date: "23/10/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=8, fig.height=4.5)
library(tidyverse)
library(kpiESR)
library(ggthemes)

uais <- c(esr.uais$Université$`Université d'Angers`, esr.uais$Université$`Université Nice - Sophia-Antipolis`)
```

Attention, ceci n'est qu'un brouillon.

```{r dotations}
df.all <- esr %>% filter(as.character(Rentrée) > 2011, Type == "Université")
df.etabs <- df.all %>% filter(UAI %in% uais)

ggplot(df.etabs,aes(x=Rentrée,y=kpi.K.resPetu)) +
  geom_boxplot(data = df.all, fill="grey", alpha=0.5) +
  geom_line(aes(group=Libellé, color=Libellé), size = 2) +
  scale_y_continuous(limits=c(2000,12000), name = "Ressources par étudiant", labels = euro_k) +
  theme_hc() + 
  theme(axis.title.x = element_blank())
```

```{r tauxdencadrement}
ggplot(df.etabs ,aes(x=Rentrée,y=kpi.K.titPetu)) +
  geom_boxplot(data = df.all, fill="grey", alpha=0.5) +
  geom_line(aes(group=Libellé, color=Libellé), size = 2) +
  scale_y_continuous(name = "Taux d'encadrement") +
  theme_hc()
```

```{r taxuressroucespropres}
ggplot(df.etabs ,aes(x=Rentrée,y=kpi.K.proPres)) +
  geom_boxplot(data = df.all, fill="grey", alpha=0.5) +
  geom_line(aes(group=Libellé, color=Libellé), size = 2) +
  scale_y_continuous(name = "Taux de ressrouces propres", labels=scales::percent) +
  theme_hc()
```